### ISSUE TITLE
Criar tela de login com o fluxo básico

### ISSUE THREAD

**Issue by GabrielAderaldo** [GabrielAderaldo/SeboBocks#3]
### Descrição:
_Criando a base e a arquitetura de projeto.
Criando uma ideia de Single-Page-Application._
### Criterio de aceite: 
_Abrir a pagina e conter uma mensagem centralizada com hello word. e apartar algum botão e mudar de pagina._
### Detalhes: 
| Prioridade | Dificuldade |
| ------------- | ------------- |
| Mediana |  2 |

### Tasks:

- [x] Criar a branch Dev
- [x] Criando a base do projeto de module
- [ ] Estudar um pouco mais sobre modules
- [ ] Estudar sobre SPA javascript vanilla 
- [ ]  implementar uma pequena pagina com um exemplo simples.
